apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
data:
  filebeat.yml: |
    filebeat.inputs:
    - type: log
      paths:
        - /var/log/nginx/*.log
      json.keys_under_root: true

    #output.elasticsearch:
    #  hosts: ["elasticsearch.monitoring.svc.cluster.local:9200"]
    #  index: "test-%{[agent.version]}-%{+yyyy.MM.dd}"

    output.logstash:
      hosts: ["logstash.monitoring.svc.cluster.local:5044"]
      index: "test-%{[agent.version]}-%{+yyyy.MM.dd}"

    setup.ilm.enabled: false
    setup.template.name: "test"
    setup.template.pattern: "test-*"

    processors:
      - add_tags:
          tags: [test]
          target: "tags"
